/* global document -- page.evaluate callbacks run in the browser */
// Renders Open Graph images (1200x630) and the Apple touch icon with Playwright.
// Usage: node scripts/og.mjs   (writes web/public/og/*.png and web/public/apple-touch-icon.png)

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { chromium } from "playwright";

// Read project data from the TypeScript source without a TS toolchain:
// the fields we need are simple literals.
const src = readFileSync("web/app/content/projects.ts", "utf8");
const projects = [
  ...src.matchAll(
    /slug: "([^"]+)",\s*name: "([^"]+)",[\s\S]*?accent: "([^"]+)",\s*accent2: "([^"]+)",[\s\S]*?fr: \{\s*tagline: "([^"]+)"/g,
  ),
].map(([, slug, name, accent, accent2, tagline]) => ({ slug, name, accent, accent2, tagline }));

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");
const inter = readFileSync(
  "node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2",
).toString("base64");

const page = ({
  eyebrow,
  title,
  subtitle,
  a1,
  a2,
  gradientTitle,
}) => `<!doctype html><html><head><style>
@font-face { font-family: Inter; src: url(data:font/woff2;base64,${inter}) format("woff2"); font-weight: 100 900; }
* { margin: 0; box-sizing: border-box; }
body { width: 1200px; height: 630px; background: #000; color: #f5f5f7; font-family: Inter, sans-serif; overflow: hidden; position: relative; }
.glow { position: absolute; inset: -30%; background:
  radial-gradient(28% 38% at 30% 62%, ${a1}, transparent 70%),
  radial-gradient(30% 40% at 78% 38%, ${a2}, transparent 70%); filter: blur(70px); opacity: .75; }
.wrap { position: relative; height: 100%; padding: 72px 80px; display: flex; flex-direction: column; justify-content: flex-end; }
.eyebrow { font-size: 30px; font-weight: 600; color: #a1a1a6; letter-spacing: .01em; }
h1 { margin-top: 10px; font-size: 104px; line-height: 1.02; font-weight: 700; letter-spacing: -0.035em; }
h1.g { background: linear-gradient(95deg,#2997ff,#a855f7 45%,#f472b6 75%,#ff9f0a); -webkit-background-clip: text; color: transparent; }
p { margin-top: 18px; font-size: 40px; font-weight: 600; letter-spacing: -0.015em; color: #e8e8ed; max-width: 980px; }
.brand { position: absolute; top: 64px; left: 80px; display: flex; align-items: center; gap: 16px; font-size: 26px; font-weight: 600; }
.mark { width: 44px; height: 44px; border-radius: 12px; display: grid; place-items: center; font-weight: 700; color: #fff;
  background: linear-gradient(135deg,#2997ff,#a855f7 60%,#f472b6); }
.url { position: absolute; top: 70px; right: 80px; font-size: 24px; color: #a1a1a6; }
</style></head><body><div class="glow"></div>
<div class="brand"><span class="mark">N</span>Nathan Chevrollier</div><div class="url">chevrolliernathan.fr</div>
<div class="wrap"><div class="eyebrow">${esc(eyebrow)}</div><h1 class="${gradientTitle ? "g" : ""}">${esc(title)}</h1>${subtitle ? `<p>${esc(subtitle)}</p>` : ""}</div>
</body></html>`;

mkdirSync("web/public/og", { recursive: true });
const browser = await chromium.launch();
const tab = await browser.newPage({ viewport: { width: 1200, height: 630 } });

async function shot(html, path) {
  await tab.setContent(html, { waitUntil: "load" });
  await tab.evaluate(() => document.fonts.ready);
  await tab.screenshot({ path });
  console.log(path);
}

await shot(
  page({
    eyebrow: "Développeur full-stack · En recherche d'alternance",
    title: "Nathan Chevrollier.",
    subtitle: "Je conçois, je construis, je déploie.",
    a1: "#2997ff",
    a2: "#a855f7",
    gradientTitle: true,
  }),
  "web/public/og/default.png",
);

for (const p of projects) {
  await shot(
    page({ eyebrow: "Projet", title: p.name, subtitle: p.tagline, a1: p.accent, a2: p.accent2 }),
    `web/public/og/${p.slug}.png`,
  );
}

// Apple touch icon from the favicon (iOS adds its own rounded mask: fill the square).
const svg = readFileSync("web/public/favicon.svg", "utf8").replace('rx="16"', 'rx="0"');
await tab.setViewportSize({ width: 180, height: 180 });
await tab.setContent(
  `<body style="margin:0">${svg.replace("<svg ", '<svg width="180" height="180" ')}</body>`,
);
await tab.screenshot({ path: "web/public/apple-touch-icon.png" });
writeFileSync("web/public/og/.generated", "Generated by scripts/og.mjs — do not edit by hand.\n");
await browser.close();
